name: Run stats tracker
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run-stats:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo builds
        uses: Swatinem/rust-cache@v2

      - name: Run Stats
        run: cargo run --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          START_TIME: ${{ vars.START_TIME }}
          END_TIME: ${{ vars.END_TIME }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }} 
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          MID_EVALS_ENDED: ${{ vars.MID_EVALS_ENDED }}
